export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const GET_INGREDIENTS = "GET_INGREDIENTS";

export const COMPLETE_PURCHASE ="COMPLETE_PURCHASE"
export const FAIL_PURCHASE ="FAIL_PURCHASE"
export const START_PURCHASE ="START_PURCHASE"

export const AUTH_START = "AUTH_START"
export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const AUTH_FAIL = "AUTH_FAIL"